In [1]:
import numpy as np

In [2]:
print("Hello World")

Hello World


In [3]:
myar=np.array([3,5,6,7,8])

In [4]:
myar

array([3, 5, 6, 7, 8])

In [5]:
myar(0)

TypeError: 'numpy.ndarray' object is not callable

In [6]:
myar[1]

5

#2D Array

In [9]:
myar=np.array([[3,4,5,6,7]])

In [10]:
myar

array([[3, 4, 5, 6, 7]])

In [11]:
myar[0,2]

5

In [12]:
myar.shape

(1, 5)

In [13]:
myar.dtype

dtype('int32')

In [14]:
myar[0,1]=99

**Insert a number in the array**

In [15]:
myar

array([[ 3, 99,  5,  6,  7]])

In [ ]:
Listarray=np.array([[1,2,3],[5,6,7],[5,4,2]])

In [16]:
Listarray

NameError: name 'Listarray' is not defined

In [17]:
listarray=np.array([[1,2,3],[5,6,7],[5,4,2]])

In [18]:
listarray

array([[1, 2, 3],
       [5, 6, 7],
       [5, 4, 2]])

In [19]:
listarray.size

9

In [20]:
np.array({2,3,4,5,6})

array({2, 3, 4, 5, 6}, dtype=object)

**20 shows that it's data type is object and most of cases we should avoid it**

In [21]:
zeros=np.zeros([2,4])

In [22]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
rng=np.arrange(12)

AttributeError: module 'numpy' has no attribute 'arrange'

In [24]:
rng=np.range(13)

AttributeError: module 'numpy' has no attribute 'range'

In [ ]:
rng= np.arrange(12)


In [26]:
rng


NameError: name 'rng' is not defined

In [27]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arrange(2,10,dtype=float)

AttributeError: module 'numpy' has no attribute 'arrange'

In [29]:
np.arange(2,10,dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
rng=np.arange(25)

In [31]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
np.arange(3,20,0.02)

array([ 3.  ,  3.02,  3.04,  3.06,  3.08,  3.1 ,  3.12,  3.14,  3.16,
        3.18,  3.2 ,  3.22,  3.24,  3.26,  3.28,  3.3 ,  3.32,  3.34,
        3.36,  3.38,  3.4 ,  3.42,  3.44,  3.46,  3.48,  3.5 ,  3.52,
        3.54,  3.56,  3.58,  3.6 ,  3.62,  3.64,  3.66,  3.68,  3.7 ,
        3.72,  3.74,  3.76,  3.78,  3.8 ,  3.82,  3.84,  3.86,  3.88,
        3.9 ,  3.92,  3.94,  3.96,  3.98,  4.  ,  4.02,  4.04,  4.06,
        4.08,  4.1 ,  4.12,  4.14,  4.16,  4.18,  4.2 ,  4.22,  4.24,
        4.26,  4.28,  4.3 ,  4.32,  4.34,  4.36,  4.38,  4.4 ,  4.42,
        4.44,  4.46,  4.48,  4.5 ,  4.52,  4.54,  4.56,  4.58,  4.6 ,
        4.62,  4.64,  4.66,  4.68,  4.7 ,  4.72,  4.74,  4.76,  4.78,
        4.8 ,  4.82,  4.84,  4.86,  4.88,  4.9 ,  4.92,  4.94,  4.96,
        4.98,  5.  ,  5.02,  5.04,  5.06,  5.08,  5.1 ,  5.12,  5.14,
        5.16,  5.18,  5.2 ,  5.22,  5.24,  5.26,  5.28,  5.3 ,  5.32,
        5.34,  5.36,  5.38,  5.4 ,  5.42,  5.44,  5.46,  5.48,  5.5 ,
        5.52,  5.54,

In [33]:
lspace=np.linspace(1,5,12)

In [34]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [35]:
np.linspace(1.,4.,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

**linspace() will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values.**

In [36]:
np.empty((4,6))

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.24610994e-306, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 1.86921143e-306],
       [6.23061763e-307, 9.34608432e-307, 1.86921007e-306,
        7.56596412e-307, 2.22520559e-306, 7.56599128e-307],
       [8.45559303e-307, 8.06613040e-308, 6.89810244e-307,
        1.22387550e-307, 2.22522596e-306, 1.69119194e-306]])

In [37]:
ide=np.identity(12)

In [38]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [39]:
ide.shape

(12, 12)

In [40]:
myar.np.arange(99)

AttributeError: 'numpy.ndarray' object has no attribute 'np'

In [41]:
arr=np.array([[3,5,6],[4,6,7]])

In [42]:
arr

array([[3, 5, 6],
       [4, 6, 7]])

In [43]:
arr.reshape(33)

ValueError: cannot reshape array of size 6 into shape (33,)

In [44]:
arr.np.arange(99)

AttributeError: 'numpy.ndarray' object has no attribute 'np'

In [45]:
arr.ravel()

array([3, 5, 6, 4, 6, 7])

In [46]:
x=[[1,2,3],[4,5,6],[7,8,3]]

In [47]:
ar=np.array(x)

In [48]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 3]])

In [49]:
ar.sum(axis=0)

array([12, 15, 12])

In [50]:
ar.sum(axis=1)

array([ 6, 15, 18])

In [51]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 3]])

**T for transpose matrix**

In [52]:
ar.flat

In [53]:
for item in ar.flat


SyntaxError: invalid syntax (<ipython-input-53-558fb6652b88>, line 1)

In [54]:
for item in ar.flat
         print(item)

SyntaxError: invalid syntax (<ipython-input-54-22136fd64a10>, line 1)

In [55]:
a=np.arange(6).reshape(2,3)

In [60]:
for x in np.nditer(a):
     print(x, end=' ')


0 1 2 3 4 5 

In [57]:
a = np.arange(6).reshape(2,3)
for x in np.nditer(a):
    print(x, end=' ')

0 1 2 3 4 5 

In [58]:
a = np.arange(6)
for x in np.nditer(a):
    print(x)

0 1 2 3 4 5 

In [61]:
a = np.arange(6)
for x in np.nditer(a):
    print(x)

0
1
2
3
4
5


In [62]:
one=np.array([1,24,666,7]) 

In [63]:
one.argmax()

2

In [64]:
one.argmin()

0

In [65]:
x=np.array([6,1,4,333,232])

In [66]:
x.argsort()

array([1, 2, 0, 4, 3], dtype=int64)

In [67]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 3]])

In [68]:
ar.argmax(axis=0)

array([2, 2, 1], dtype=int64)

In [69]:
ar.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [70]:
ar.argmax(axis=1)

array([2, 2, 1], dtype=int64)

In [71]:
ar.argmax(axis=1)

array([2, 2, 1], dtype=int64)

In [72]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [73]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 2],
       [2, 2, 1]], dtype=int64)

In [74]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [3]])

In [75]:
ar2=np.array([[1,2,1],[3,1,1],[2,1,4]])

In [76]:
ar2

array([[1, 2, 1],
       [3, 1, 1],
       [2, 1, 4]])

In [77]:
ar+ar2

array([[2, 4, 4],
       [7, 6, 7],
       [9, 9, 7]])

In [78]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 1.73205081]])

In [79]:
np.where(ar>3)

(array([1, 1, 1, 2, 2], dtype=int64), array([0, 1, 2, 0, 1], dtype=int64))

In [83]:
np.count_nonzero(ar)

9

In [81]:
import sys

In [82]:
py_ar=[0,3,44,2]
np_ar=np.ar(py_ar)

AttributeError: module 'numpy' has no attribute 'ar'

In [85]:
py_ar=[0,3,44,5]


In [ ]:
np_ar=np.array(py_ar)

In [86]:
sys.getsizeof(1)* len(py_ar)

112

In [98]:
np_ar.itemsize * np_ar.size

NameError: name 'np_ar' is not defined

In [97]:
sys.getsizeof(1) * len(np_ar)

NameError: name 'np_ar' is not defined

In [91]:
x = np.zeros((3, 5, 2)

SyntaxError: unexpected EOF while parsing (<ipython-input-91-f6f7c98dd876>, line 1)

In [92]:
x.size

5

In [93]:
x = np.zeros((3, 5, 2), dtype=np.complex128)
x.size

30

In [95]:
np.prod(x.shape)

30

In [99]:
arr = np.array([[1, 2], [3, 4]])

In [100]:
arr.dtype

dtype('int32')

In [101]:
arr.itemsize

4

In [102]:
arr.itemsize * arr.size

16

**BinGo**